### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by lufinkey** [Doraku/DefaultDocumentation#167]
When trying to generate documentation using the dotnet tool, I get this error.

Config:
```
{
	"GeneratedPages": "Namespaces,Types",
	"AssemblyFilePath": "./Temp/bin/Debug/MegaParticle.Utils.dll",
	"ProjectDirectoryPath": "../../",
	"DocumentationFilePath": "./Temp/bin/Debug/MegaParticle.Utils.xml",
	"OutputDirectoryPath": "../../Documentation~",
	"Markdown.NestedTypeVisibilities": "DeclaringType"
}
```

Full stack trace:
```
At D:\Code\PokerVRLD\Modules\MegaParticle.Utils\Samples~\ExampleProject\RebuildDocumentation.ps1:3 char:1
+ defaultdocumentation --ConfigurationFilePath $configPath
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...ins no elements:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at DefaultDocumentation.Internal.DocItemReader.<.ctor>g__IsGenerated|5_0(IEntity entity, <>c__DisplayClass5_0& ) in 
D:\a\DefaultDocumentation\DefaultDocumentation\source\DefaultDocumentation.Common\Internal\DocItemReader.cs:line 35
   at DefaultDocumentation.Internal.DocItemReader..ctor(Settings settings) in 
D:\a\DefaultDocumentation\DefaultDocumentation\source\DefaultDocumentation.Common\Internal\DocItemReader.cs:line 157
   at DefaultDocumentation.Internal.DocItemReader.GetItems(Settings settings) in 
D:\a\DefaultDocumentation\DefaultDocumentation\source\DefaultDocumentation.Common\Internal\DocItemReader.cs:line 354
   at DefaultDocumentation.Generator..ctor(Target loggerTarget, IRawSettings settings) in 
D:\a\DefaultDocumentation\DefaultDocumentation\source\DefaultDocumentation.Common\Generator.cs:line 116
   at DefaultDocumentation.Generator.Execute(Target loggerTarget, IRawSettings settings) in 
D:\a\DefaultDocumentation\DefaultDocumentation\source\DefaultDocumentation.Common\Generator.cs:line 195
   at DefaultDocumentation.Program.<>c.<Main>b__0_1(SettingsArgs a) in D:\a\DefaultDocumentation\DefaultDocumentation\source\DefaultDocumentation.Console\Program.cs:line 24
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at DefaultDocumentation.Program.Main(String[] args) in D:\a\DefaultDocumentation\DefaultDocumentation\source\DefaultDocumentation.Console\Program.cs:line 18
```

**Comment by Doraku** [comment]
latest beta version (1.0.0-beta04) should fix the error by ignoring the member but I'm curious why the the type is missing. Is it a private project or is it possible to know the member it fails for? You can set the [log level](https://github.com/Doraku/DefaultDocumentation?tab=readme-ov-file#loglevel) to `Debug`.

**Comment by lufinkey** [comment]
Also I tested 1.0.0-beta04 and it seems to be fixed. Thanks!

**Comment by Doraku** [comment]
The `ILayoutElement` is a unity interface I guess 🤔 ? Is it a unity package built by unity itself or are you referencing it manually so you can compile/generate the documentation outside of unity?

**Comment by lufinkey** [comment]
Sorry missed this notification. This is code for a unity project, and yea `ILayoutElement` is an interface provided by unity. I'm using this in the visual studio project that gets generated by unity.

**Comment by Doraku** [comment]
I'll see if I can replicate this issue and understand why the unity dll is not loaded in DefaultDocumentation to access its metadata, I know they are regenerating the csproj and managing the references a little different 🤔
