### ISSUE TITLE
Any chance for Mac support?

### ISSUE THREAD

**Issue by LittleCornerDev** [Doraku/DefaultDocumentation#18]
Just wondering if Mac support is on the timeline?  I was excited to try this library as I had the netcore requirement in my Xamarin.Forms app and nuget installs fine, but .exe from nuget crashes the build in Visual Studio for Mac.

**Comment by Doraku** [comment]
Hum normally it is supposed to work for Mac/Linux with netcore, that means I probably messed up the .targets >_> I don't have access to a linux or mac machine so I did it blind by copying examples I had seen that were supposed to work
https://github.com/Doraku/DefaultDocumentation/blob/a15a307e06f0a0130cce90ca79d21fb43209c59a/source/DefaultDocumentation/build/DefaultDocumentation.targets#L5
It should use the dll with dotnet command instead of the exe for you, I will try to check what is wrong.

**Comment by Doraku** [comment]
Or does it actually succeed in starting the DefaultDocumentation process but it crashs for some other reason?

**Comment by LittleCornerDev** [comment]
Ok, I actually got confused between 2 different .NET projects in my solution.  The unit tests were on .NET Core 3.1.  The main project on which I had tried this library with is actually using .NET Standard 2.0.   Could that be why the .exe tried to run?  

Here is the exact error message upon build but with the local-specific parts replaced with placeholders:

> {HOME_DIR}/.nuget/packages/defaultdocumentation/0.6.3/build/DefaultDocumentation.targets(5,5): Error MSB3073: The command "mono "{HOME_DIR}/.nuget/packages/defaultdocumentation/0.6.3/build/../tools/DefaultDocumentation.exe" /assembly:"{PROJECT_PATH}/bin/Debug/netstandard2.0/{PROJECT_NAME}.dll" /xml:"{PROJECT_PATH}/bin/Debug/netstandard2.0/{PROJECT_NAME}.xml" /output:"" /home:"" /fileNameMode:"FullName" /nestedTypeVisibility:"Namespace" /baselink:"" /linksfile:""" exited with code 1. (MSB3073) ({PROJECT_NAME})

**Comment by LittleCornerDev** [comment]
It is using .dll instead of .exe after switching the target framework to .NET Standard 2.1, but somehow still getting the MSB3073 error:

> {HOME_DIR}/.nuget/packages/defaultdocumentation/0.6.3/build/DefaultDocumentation.targets(18,5): error MSB3073: The command "dotnet "{HOME_DIR}/.nuget/packages/defaultdocumentation/0.6.3/build/../tools/DefaultDocumentation.dll" /assembly:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.dll" /xml:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.xml" /output:"" /home:"" /fileNameMode:"FullName" /nestedTypeVisibility:"Namespace" /baselink:"" /linksfile:""" exited with code 134. [{PROJECT_PATH}/{PROJECT_NAME}.csproj]

I will try to investigate to see if there's anything else wonky on my end.  I am fairly new to .NET though, so if you have any ideas as to what I could be missing or setting up incorrectly, please let me know :-)

**Comment by Doraku** [comment]
hum so the detection of mono/netcore is already questionable, guess I will just remove the mono line and expect netcore to be present.
So I guess it is starting DefaultDocumentation correctly in your second case, maybe I am using something (path, file, ...) that does not work correctly on mac. I will try to steal the mac of my SO to put Visual Studio on it and test what could be wrong lol.
If you want to look into it, you can d/l this repo and try to run in debug DefaultDocumentation by giving him the same argument: /assembly:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.dll" /xml:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.xml" (you can ignore the rest)
Remove this line too or It will probably complains since you are on mac
https://github.com/Doraku/DefaultDocumentation/blob/a15a307e06f0a0130cce90ca79d21fb43209c59a/source/DefaultDocumentation/DefaultDocumentation.targets#L6
Sorry to ask you to do this if you have the time >_<

Btw [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) is the correspondance between netstandard and netcore/framework, it is kind of a mess sadly :/

**Comment by Doraku** [comment]
Actually I don't know what the error code are on mac but those value seems strange, can you try just to run the full command in a terminal to see if it gives you something less cryptic? Just this part
>dotnet "{HOME_DIR}/.nuget/packages/defaultdocumentation/0.6.3/build/../tools/DefaultDocumentation.dll" /assembly:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.dll" /xml:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.xml"

**Comment by LittleCornerDev** [comment]
Happy to help, and happy for the help :-)

Running `dotnet "{HOME_DIR}/.nuget/packages/defaultdocumentation/0.6.3/build/../tools/DefaultDocumentation.dll" /assembly:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.dll" /xml:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.xml"`

has the following error:

> Unhandled exception. ICSharpCode.Decompiler.Metadata.AssemblyResolutionException: Failed to resolve assembly: 'Xamarin.Forms.Xaml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.ResolveInternal(IAssemblyReference name)
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.FindAssemblyFile(IAssemblyReference name)
   at ICSharpCode.Decompiler.Metadata.UniversalAssemblyResolver.Resolve(IAssemblyReference name)
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(PEFile mainModule, IAssemblyResolver assemblyResolver, TypeSystemOptions typeSystemOptions)
   at ICSharpCode.Decompiler.TypeSystem.DecompilerTypeSystem..ctor(PEFile mainModule, IAssemblyResolver assemblyResolver)
   at ICSharpCode.Decompiler.CSharp.CSharpDecompiler.CreateTypeSystemFromFile(String fileName, DecompilerSettings settings)
   at DefaultDocumentation.DocumentationGenerator..ctor(String assemblyFilePath, String documentationFilePath, String homePageName, FileNameMode fileNameMode, NestedTypeVisibility nestedTypeVisibility, String linksFiles)
   at DefaultDocumentation.Program.Main(String[] args)
Abort trap: 6

I am not sure why the decompiler is trying to resolve the Xaml assembly or why it thinks it is missing though.

**Comment by Doraku** [comment]
DefaultDocumentation loads your produced binary to get extra informations like return types and parameters types, things that are not present in the xml comments to produce a more complete documentation, so I guess you are using some types of this assembly as return/parameter/parent type in your code. Is the code you are trying to apply it on public by any chance so I can see if I can reproduce this error? it is really strange that it fails to load dependencies, is the Xamarin.Forms.Xaml library in the ouput folder of your project?

**Comment by LittleCornerDev** [comment]
It is a project using the Xamarin.Forms framework, so Xamarin.Forms.Xaml is just one of many Xamarin.Forms libs the app uses.

There are no other libraries in the output folder.  It just has my project dll, json, pdb, and xml files.

Alas, the code is in a private repo for a pre-alpha app :-(

Maybe it is something that can be fixed by something in the build settings?

**Comment by Doraku** [comment]
I am sorry for the slow news, got a little pup in our home this week end and free time has just vanished ^^"
It should work without any special settings as those dlls are probably in your GAC (or its equivalent on mac). I will try to create a simple xamarin project for android to check if I can reproduce on my machine, if not I will try on my SO's mac (hopefully this week).

**Comment by LittleCornerDev** [comment]
No worries.  Thanks for the update!

**Comment by Doraku** [comment]
Just tried with a android xamarin project and while I don't have the same missing dll as you I do have a similar problem: `Failed to resolve assembly: Mono.Android` in my case.  I will see what's up with that.

**Comment by Doraku** [comment]
Hopefully the [latest version](https://www.nuget.org/packages/DefaultDocumentation/0.6.4) should fix your problem, it did the trick for me on windows. Tell me if you still have an error :)

**Comment by LittleCornerDev** [comment]
Thanks for the update!  

When running the latest version via `dotnet "{HOME_DIR}/.nuget/packages/defaultdocumentation/0.6.4/build/../tools/DefaultDocumentation.dll" /assembly:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.dll" /xml:"{PROJECT_PATH}/bin/Debug/netstandard2.1/{PROJECT_NAME}.xml"`,

I now get a different error:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) (One or more errors occurred. (Object reference not set to an instance of an object.)) (One or more errors occurred. (Object reference not set to an instance of an object.)) (One or more errors occurred. (Object reference not set to an instance of an object.)) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.Documentation.IdStringProvider.GetIdString(IEntity entity)
   at DefaultDocumentation.DocumentationWriter.GetTypeLink(IType type)
   at DefaultDocumentation.Model.FieldDocItem.WriteDocumentation(DocumentationWriter writer)
   at DefaultDocumentation.DocumentationGenerator.<>c__DisplayClass9_0.<WriteDocumentation>b__1(DocItem i)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at DefaultDocumentation.DocumentationGenerator.WriteDocumentation(String outputFolderPath)
   at DefaultDocumentation.Program.Main(String[] args)
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.Documentation.IdStringProvider.GetIdString(IEntity entity)
   at DefaultDocumentation.DocumentationWriter.GetTypeLink(IType type)
   at DefaultDocumentation.Model.FieldDocItem.WriteDocumentation(DocumentationWriter writer)
   at DefaultDocumentation.DocumentationGenerator.<>c__DisplayClass9_0.<WriteDocumentation>b__1(DocItem i)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

 ---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.Documentation.IdStringProvider.GetIdString(IEntity entity)
   at DefaultDocumentation.DocumentationWriter.GetTypeLink(IType type)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at DefaultDocumentation.Model.TypeDocItem.WriteDocumentation(DocumentationWriter writer)
   at DefaultDocumentation.DocumentationGenerator.<>c__DisplayClass9_0.<WriteDocumentation>b__1(DocItem i)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

 ---> (Inner Exception #3) System.NullReferenceException: Object reference not set to an instance of an object.
   at ICSharpCode.Decompiler.Documentation.IdStringProvider.GetIdString(IEntity entity)
   at DefaultDocumentation.DocumentationWriter.GetTypeLink(IType type)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at DefaultDocumentation.Model.TypeDocItem.WriteDocumentation(DocumentationWriter writer)
   at DefaultDocumentation.DocumentationGenerator.<>c__DisplayClass9_0.<WriteDocumentation>b__1(DocItem i)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

Abort trap: 6
```


Please let me know if there is anything else I can do on my end.

**Comment by Doraku** [comment]
huhum, by any chance do you have pointers in your type members, method parameters or return types?

**Comment by LittleCornerDev** [comment]
Do you mean `<see cref|href|langword>`?  I use those everywhere.

The only tag I use that I know is not supported as per the [overview](https://github.com/Doraku/DefaultDocumentation#overview), is `<list>`.

There were some xml typos that running the build gave warnings about, so I fixed them.  There are no more XML warnings, but the error remains the same. 

I think `<list>` gets ignored as far as I can tell?

**Comment by Doraku** [comment]
No `<see cref|href|langword>` are already handled correctly.
`list` should be printed as is instead of using the markdown syntax because I am lazy but I should really get it done ^^"

I was talking about `int* DummyMethod(void* value)` kind of pointer, using the unsafe directive. From your callstack I saw that I forgot about them and fixed the documentation generation for them, but if you don't have things like that in your code then I will have to search some more.

**Comment by LittleCornerDev** [comment]
Oh, I see.  I double-checked and searched in files for `*`, and it is only in`/* ... */` multi-line comments.

In case it is relevant, the fanciest method signature I have is an extension method with a generic `typeparam` and a `dynamic` return type: `public static dynamic TrimObject<T>(this T objectToTrim) `

Also, not sure in which order the `md` files are generated, but I just noticed that the alphabetically last `md` file listed was for a method `protected async override void OnAppearing()`, but the md only says `protected override void OnAppearing();`.    Could the issue be with the `async` descriptor?

**Comment by Doraku** [comment]
I tried with dynamic/async/generic it works for me :/ Documentation pages are generated in parallel which is why when it fails you may not have the same successful files every time. 
I fixed the pointer problem, also I changed the exception thrown so it actually tells which member fails its documentation generation, maybe it will be easier to pinpoint the problem! Could you build latest sources and run it on your project? Hopefully we will find the elusive problem :)

**Comment by LittleCornerDev** [comment]
Is there a new nuget I should use?  The latest I see is 0.6.5.

**Comment by Doraku** [comment]
Just added v0.6.6 on nuget, didn't want to create a new package until fixing your problem but oh well ^^"

**Comment by LittleCornerDev** [comment]
Ah, sorry, I just assumed nuget.  I can do a clone and update local references instead next time.  

Error messages now mention the method/property names where doc writing fails.  Four names were mentioned:

Two are typical class declarations using `Xamarin.Forms`:

```
	/// <summary>
	/// 	Primary launcher class for this <see cref="Xamarin.Forms.Application"/>.
	/// </summary>
	public partial class App : Application { ... }
```
```
	/// <summary>
	/// 	Handles the page where an <see cref="Item"/> is added.
	/// </summary>
	[XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class ItemAddPage : ContentPage { ... }
```

The other two are variable declarations using `Autofac`: 

```
		/// <summary>
		/// 	Builder for component registrations.
		/// </summary>
		public ContainerBuilder Builder = new ContainerBuilder();
```

```
		/// <summary>
		/// 	Component manager created by <see cref="Builder"/>.
		/// </summary>
		public static IContainer Container;
```

Does that help?

**Comment by Doraku** [comment]
yes perfect I replicated the error! Xamarin types appear as unknown for some reason (probably because it failed silently to load those dependencies) but I should be able to create the documentation anyway.

**Comment by Doraku** [comment]
woof finally, sorry for making you jump so many hoops, at least the worst default case is handled even if it is not perfect for now.
For the first two cases (App and ItemAddPage) those types inherit xamarin types so even though DefaultDocumentation couldn't load the dependencies for some reason we can still generate a link to the msdn api by using the type full name (I am sure this will generate bogus link for generic types though, there is place for improvement).
For the other two, we can't know where the documentation for the Autofac library is so a bogus link is generated but at least it doesn't crash anymore. Next step would be to finish implementing #7 so you can pass a file to DefaultDocumentation which say "for this external type (which is not from microsoft) the documentation page is here", but no ETA on this feature ^^"

**Comment by LittleCornerDev** [comment]
ah, i see.  i was debating whether i had to switch external refs from `cref`s to `href`s.  they seem to be handled differently by different doc tools, so I haven't focused on worrying about them too much.

i can confirm that the latest nuget 0.6.7 now successfully generates all markdown files with no errors for my project.

thanks so much for taking time to work on this! :-)
