### ISSUE TITLE
Forward inheritance hierarchy from a parent

### ISSUE THREAD

**Issue by nxrighthere** [Doraku/DefaultDocumentation#19]
I wonder if we can implement a forward inheritance hierarchy representation from a parent, similar to DocFX:
![z](https://user-images.githubusercontent.com/8279330/82946251-72ad1a00-9fb7-11ea-80f5-dfdb5e1977dc.PNG)
Currently, it's hard to find all derived classes across a large framework.

**Comment by nxrighthere** [comment]
Maybe something like this:

![x](https://user-images.githubusercontent.com/8279330/82948743-cd487500-9fbb-11ea-8629-70173698e3d1.PNG)

Markdown:
```markdown
&#8627; [System.Object](https://docs.microsoft.com/en-us/dotnet/api/System.Object 'System.Object') </br>
&ensp;&ensp; &#8627; [Actor](./UnrealEngine-Framework-Actor.md 'UnrealEngine.Framework.Actor') </br>
&ensp;&ensp;&ensp;&ensp; &#8627; [AmbientSound](./UnrealEngine-Framework-AmbientSound.md 'UnrealEngine.Framework.AmbientSound') </br>
&ensp;&ensp;&ensp;&ensp; &#8627; [Brush](./UnrealEngine-Framework-Brush.md 'UnrealEngine.Framework.Brush') </br>
&ensp;&ensp;&ensp;&ensp; &#8627; [Camera](./UnrealEngine-Framework-Camera.md 'UnrealEngine.Framework.Camera') </br>
&ensp;&ensp;&ensp;&ensp; &#8627; [Controller](./UnrealEngine-Framework-Controller.md 'UnrealEngine.Framework.Controller') </br>
&ensp;&ensp;&ensp;&ensp; &#8627; [Light](./UnrealEngine-Framework-Light.md 'UnrealEngine.Framework.Light') </br>
&ensp;&ensp;&ensp;&ensp; &#8627; [Pawn](./UnrealEngine-Framework-Pawn.md 'UnrealEngine.Framework.Pawn') </br>
```

**Comment by nxrighthere** [comment]
Also, it probably makes sense to not add a link to the currently opened page of a class (the `Actor` in the example above).

**Comment by Doraku** [comment]
Since we only have to check for the current assembly types this should be easy to add. And actually microsoft also have this information in their api documentation ([Derived section](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1?view=netframework-4.5)) but presented differently. Is the msdn api representation ok for you too as everything else is in their style?

**Comment by nxrighthere** [comment]
Yea, sure! Seems fine.

**Comment by nxrighthere** [comment]
@Doraku Nice job, thank you very much!

**Comment by nxrighthere** [comment]
@Doraku Thank you for your contribution!

https://github.com/nxrighthere/UnrealCLR

Credit at the bottom of the page. ❤️

**Comment by Doraku** [comment]
Huhu UnrealCLR is finally out in the open? congrats on the preview release! And thank you for the mention ;)

**Comment by nxrighthere** [comment]
Sorry for bumping the issue.
```
C:\Users\Tanner\Desktop\Projects\DevPrograms\UnrealFolder\UnrealCLR\Source\Managed\Framework>dotnet publish --configuration Release --framework netcoreapp3.1 --output "C:\Users\Tanner\Desktop\Projects\My Projects SSD\Unreal Projects\RPGAIProtoUECPP\Plugins\UnrealCLR\Managed"
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\Tanner\Desktop\Projects\DevPrograms\UnrealFolder\UnrealCLR\Source\Managed\Framework\UnrealEngine.Framework.csproj (in 6.53 sec).
  UnrealEngine.Framework -> C:\Users\Tanner\Desktop\Projects\DevPrograms\UnrealFolder\UnrealCLR\Source\Managed\Framework\bin\Release\UnrealEngine.Framework.dll

  Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Error while writing documentation for UnrealEngine.Framework.Debug.DrawBox(System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Quaternion, System.Drawing.Color, bool, float, byte, float) ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Tanner\Desktop\Projects\DevPrograms\UnrealFolder\UnrealCLR\Source\Managed\Framework\docs\API\UnrealEngine-Framework-Debug-DrawBox(System-Numerics-Vector3_System-Numerics-Vector3_System-Numerics-Quaternion_System-Drawing-Color_bool_float_byte_float).md'.
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
     at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
     at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
     at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
     at DefaultDocumentation.DocumentationWriter.Dispose()
     at DefaultDocumentation.DocumentationGenerator.<>c__DisplayClass9_0.<WriteDocumentation>b__1(DocItem i)
     --- End of inner exception stack trace ---
     at DefaultDocumentation.DocumentationGenerator.<>c__DisplayClass9_0.<WriteDocumentation>b__1(DocItem i)
     at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
     at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
     at System.Linq.Parallel.SpoolingTaskBase.Work()
     at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
     at System.Threading.Tasks.Task.Execute()
     --- End of inner exception stack trace ---
     at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
     at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
     at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
     at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
     at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
     at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
     at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStrea
```
One of the users reported it. Any ideas?

**Comment by nxrighthere** [comment]
It seems that this is due to the exceeded file path length, which is 260 characters.

**Comment by Doraku** [comment]
Yes that definitely seems like a path too long for Windows, even though the exception doesn't state exactly so. It is not perfect but there is the DefaultDocumentationFileNameMode he could use with the value Md5 to make shorter static names.
Actually a coworker had a problem like this recently and found some other workaround, I will see what's up with  that and if it can be applied to DefaultDocumentation.
