### ISSUE TITLE
KeyNotFoundException exception when generating documentation

### ISSUE THREAD

**Issue by Hekku2** [Doraku/DefaultDocumentation#3]
I encountered `KeyNotFoundException` when I was trying to use this library to generate .md-files. I assume this is caused by missing comments from classes.

```
  ValidationLibrary -> C:\Projects\repository-validator\ValidationLibrary\bin\Debug\netstandard2.0\ValidationLibrary.dll

  Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key 'T:ValidationLibrary.GitHubConfiguration' was not present in the dictionary.
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
     at DefaultDocumentation.Converter.Parse(XDocument document)
     at DefaultDocumentation.Converter..ctor(XDocument document, String outputPath)
     at DefaultDocumentation.Converter.Convert(XDocument document, String outputPath)
     at DefaultDocumentation.Program.Main(String[] args)
C:\Users\hjni.PROTACON\.nuget\packages\defaultdocumentation\0.4.2\build\DefaultDocumentation.targets(7,5): error MSB3073: The command "dotnet "C:\Users\hjni.PROTACON\.nuget\packages\defaultdocumentation\0.4.2\build\..\tools\DefaultDocumentation.dll" /xml:"obj\Debug\netstandard2.0\ValidationLibrary.xml" /markdown:""" exited with code -532462766. [C:\Projects\repository-validator\ValidationLibrary\ValidationLibrary.csproj]
```

**Comment by Doraku** [comment]
Indeed, I took a look at your project, types `RepositoryValidator` and `GitHubConfiguration` are missing a summary documentation.
Still I guess it's a pain that it doesn't go to the end if anything is missing. I think I will relax this a little, after all visual is already giving warning if you are missing some documentation on public members.

**Comment by Doraku** [comment]
Last release [v0.4.3](https://github.com/Doraku/DefaultDocumentation/releases/tag/v0.4.3) should take care of this.

**Comment by Hekku2** [comment]
Thanks, this seems to work!
