### ISSUE TITLE
Setting GenerateDocumentationFile to false causes a crash

### ISSUE THREAD

**Issue by Ellpeck** [Doraku/DefaultDocumentation#34]
I would expect DefaultDocumentation to do nothing if GenerateDocumentationFile is set to false, but instead, it produces the following exception:
```
0>"C:\Users\Julian\.nuget\packages\defaultdocumentation\0.6.12\build\../tools/DefaultDocumentation.exe" /assembly:"D:\PROGRAMMING\TinyLife\TinyLife\bin\Debug\netcoreapp3.0\Tiny Life.dll" /xml:"" /output:"" /home:"" /fileNameMode:"FullName" /nestedTypeVisibility:"Namespace" /invalidCharReplacement:""
0>parameters:
0>	/assembly:{assembly file path}
0>	/xml:{xml documentation file path}
0>optional parameters:
0>	/output:{DefaultDocumentation output folder}
0>	/home:{DefaultDocumentation home page name}
0>	/fileNameMode:{FullName | Name | Md5}
0>	/nestedTypeVisibility:{Namespace | DeclaringType | Everywhere}
0>	/invalidCharReplacement:{the string used to replace invalid char for file names}
0>	/baseLink:{base link path used if generating a links file}
0>	/linksFile:{links file path}
0>	/externalLinks:{links files for element outside of this assembly, separated by '|'}
0>
0>Unhandled Exception: System.ArgumentException: The path is not of a legal form.
0>   at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
0>   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
0>   at System.IO.Path.GetFullPathInternal(String path)
0>   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
0>   at DefaultDocumentation.Program.Main(String[] args)
0>C:\Users\Julian\.nuget\packages\defaultdocumentation\0.6.12\build\DefaultDocumentation.targets(18,5): Error MSB3073 : The command ""C:\Users\Julian\.nuget\packages\defaultdocumentation\0.6.12\build\../tools/DefaultDocumentation.exe" /assembly:"D:\PROGRAMMING\TinyLife\TinyLife\bin\Debug\netcoreapp3.0\Tiny Life.dll" /xml:"" /output:"" /home:"" /fileNameMode:"FullName" /nestedTypeVisibility:"Namespace" /invalidCharReplacement:""" exited with code -532462766.
```

**Comment by Doraku** [comment]
Thanks, big oversight of me! I will fix the target.
